const BLOCKED_DOMAINS = new Set([
  "guerrillamail.com", "tempmail.com", "throwaway.email", "temp-mail.org",
  "mailinator.com", "yopmail.com", "dispostable.com", "sharklasers.com",
  "guerrillamailblock.com", "grr.la", "guerrillamail.info",
  "guerrillamail.biz", "guerrillamail.de", "guerrillamail.net",
  "guerrillamail.org", "guerrillamail.ro", "guerrillamailstore.com",
  "guerrillamail.tv", "guerrillamail.us", "guerrillamailproxy.com",
  "guerrillamails.com", "guerrillamailus.com", "harakirimail.com",
  "hidemail.de", "hmamail.com", "hopemail.biz", "hot-mail.cf",
  "hot-mail.co.uk", "hot-mail.com", "hot-mail.gq", "hot-mail.ml",
  "hotmial.com", "hushmail.com", "inbax.tk", "inbox.si",
  "inboxclean.com", "inboxclean.org", "inboxproxy.com",
  "incognitomail.com", "incognitomail.org", "insorg-mail.info",
  "jetable.com", "jetable.fr.nf", "jetable.net", "jetable.org",
  "jnxjn.com", "jourrapide.com", "junk1e.com", "junkmail.com",
  "junkmail.ga", "junkmail.gq", "kasmail.com", "kaspop.com",
  "keepmymail.com", "killmail.com", "killmail.net", "klassmaster.com",
  "klassmaster.net", "klzlk.com", "kook.ml", "kurzepost.de",
  "letthemeatspam.com", "lifebyfood.com", "link2mail.net", "litedrop.com",
  "lol.ovpn.to", "lortemail.dk", "lovemeleaveme.com", "lukop.dk",
  "mail-temporaire.fr", "mail.mezimages.net", "mail.zp.ua",
  "mail114.net", "mail21.cc", "mail333.com", "mail4trash.com",
  "mailbidon.com", "mailblocks.com", "mailblog.biz", "mailbucket.org",
  "mailcat.biz", "mailcatch.com", "maildrop.cc", "maildrop.cf",
  "maildrop.club", "maildrop.ga", "maildrop.gq", "maildrop.ml",
  "maileater.com", "mailexpire.com", "mailfa.tk", "mailfree.ga",
  "mailfree.gq", "mailfree.ml", "mailfreeonline.com", "mailguard.me",
  "mailhazard.com", "mailhz.me", "mailin8r.com", "mailinater.com",
  "mailinator.net", "mailinator.org", "mailinator.us", "mailinator2.com",
  "mailincubator.com", "mailismagic.com", "mailmate1.net", "mailme24.com",
  "mailmetrash.com", "mailmoat.com", "mailnator.com", "mailnesia.com",
  "mailnull.com", "mailorg.org", "mailpick.biz", "mailproxsy.com",
  "mailquack.com", "mailrock.biz", "mailsac.com", "mailscrap.com",
  "mailshell.com", "mailsiphon.com", "mailslite.com", "mailtemp.info",
  "mailtome.de", "mailtothis.com", "mailtrash.net", "mailtv.net",
  "mailtv.tv", "mailuntil.com", "mailzilla.com", "makemetheking.com",
  "manifestgenerator.com", "manybrain.com", "mbx.cc", "meltmail.com",
  "mezimages.net", "migmail.pl", "migumail.com", "mindless.com",
  "mintemail.com", "mmmmail.com", "moakt.com", "moncourrier.fr.nf",
  "monemail.fr.nf", "monmail.fr.nf", "monumentmail.com", "mx0.wwwnew.eu",
  "my10minutemail.com", "myalias.pw", "mycleaninbox.net",
  "myemailboxy.com", "mymail-in.net", "mymailoasis.com", "mymailp.com",
  "mynetstore.de", "mypacks.net", "mypartyclip.de", "myphantom.com",
  "mysamp.de", "myspaceinc.com", "myspaceinc.net", "myspaceinc.org",
  "myspacepimpedup.com", "mytemp.email", "mytempemail.com",
  "mytempmail.com", "mytempmail.de", "mytempmail.org", "mytempmails.com",
  "mytmp.email", "mytrashmail.com", "nabala.com", "neomailbox.com",
  "nepwk.com", "netmails.com", "netmails.net", "neverbox.com",
  "nice-4u.com", "nincsmail.hu", "no-spam.ws", "nomail.xl.cx",
  "nomail2me.com", "nomorespamemails.com", "nonspam.eu", "nonspammer.de",
  "noref.in", "nospam.ze.tc", "nospam4.us", "nospamfor.us",
  "nospammail.net", "nospamthanks.info", "nowmymail.com",
  "nurfuerspam.de", "nuts22.com", "nyc.com", "nyxmail.com",
  "odnorazovoe.ru", "oneoffemail.com", "onewaymail.com", "oopi.org",
  "otherinbox.com", "ourklips.com", "outlawspam.com", "pancakemail.com",
  "pjjkp.com", "pookmail.com", "privacy.net", "privatdemail.net",
  "proxymail.eu", "prtnx.com", "punkass.com", "quickinbox.com",
  "quickmail.nl", "reallymymail.com", "recursor.net", "regbypass.com",
  "rejectmail.com", "reliable-mail.com", "rhyta.com", "rmqkr.net",
  "royal.net", "rtrtr.com", "s0ny.net", "safe-mail.net",
  "safersignup.de", "safetymail.info", "safetypost.de", "sandelf.de",
  "saynotospams.com", "scatmail.com", "schafmail.de", "schrott-email.de",
  "secretemail.de", "secure-mail.biz", "secure-email.eu",
  "selfdestructingmail.com", "sendspamhere.com", "shiftmail.com",
  "shitmail.me", "shitmail.org", "shitware.nl", "shortmail.net",
  "sibmail.com", "sinnlos-mail.de", "skeefmail.com", "slopsbox.com",
  "slutty.horse", "smashmail.de", "smellfear.com", "snakemail.com",
  "sneakemail.com", "sneakymail.de", "snkmail.com", "sofimail.com",
  "sofort-mail.de", "sogetthis.com", "soodonims.com", "spam.su",
  "spam4.me", "spamavert.com", "spambob.com", "spambob.net",
  "spambob.org", "spambog.com", "spambog.de", "spambog.ru",
  "spambog.us", "spambot.me", "spambums.com", "spamcannon.com",
  "spamcannon.net", "spamcero.com", "spamcorptastic.com", "spamcowboy.com",
  "spamcowboy.net", "spamcowboy.org", "spamday.com", "spamex.com",
  "spamgoes.in", "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "spamherelots.com", "spamhereplease.com", "spamhole.com", "spamify.com",
  "spaminator.de", "spaml.com", "spaml.de", "spammotel.com",
  "spamobox.com", "spamoff.de", "spamslicer.com", "spamspot.com",
  "spamstack.net", "spamthis.co.uk", "spamthisplease.com",
  "spamtrail.com", "spamtrap.ro", "spoofmail.de", "stuffmail.de",
  "superrito.com", "superstachel.de", "suremail.info", "teleworm.com",
  "teleworm.us", "temp-mail.org", "temp-mail.ru", "tempail.com",
  "tempemail.biz", "tempemail.com", "tempemail.net", "tempemail.org",
  "tempemailbox.com", "tempinbox.com", "tempmail.eu", "tempmail.it",
  "tempmail2.com", "tempmaildemo.com", "tempmailer.com", "tempmailer.de",
  "tempomail.fr", "temporarily.de", "temporarioemail.com.br",
  "temporaryemail.net", "temporaryemail.us", "temporaryforwarding.com",
  "temporaryinbox.com", "temporarymailaddress.com", "thc.st",
  "thecloudindex.com", "thetempmail.com", "throwawayemailaddress.com",
  "tizi.com", "tmailinator.com", "toiea.com", "toomail.biz",
  "trash-amil.com", "trash-mail.at", "trash-mail.com", "trash-mail.de",
  "trash-me.com", "trash2009.com", "trashdevil.de", "trashemail.de",
  "trashmail.at", "trashmail.com", "trashmail.de", "trashmail.me",
  "trashmail.net", "trashmail.org", "trashmail.ws", "trashmailer.com",
  "trashymail.com", "trashymail.net", "trillianpro.com", "turual.com",
  "twinmail.de", "tyldd.com", "umail.net", "venompen.com",
  "veryrealliemail.com", "vpn.st", "vsimcard.com", "vubby.com",
  "weg-werf-email.de", "wegwerfadresse.com", "wegwerfemail.com",
  "wegwerfemail.de", "wegwerfmail.de", "wegwerfmail.net",
  "wegwerfmail.org", "wh4f.org", "wuzup.net", "wuzupmail.net",
  "wwwnew.eu", "xagloo.com", "xemaps.com", "xents.com",
  "xmaily.com", "xoxy.net", "yapped.net", "yep.it",
  "yomail.info", "yomp.com", "yopmail.fr", "yopmail.gq",
  "yopmail.net", "you-spam.com", "ypmail.webarnak.fr.eu.org",
  "yuurok.com", "zehnminutenmail.de", "10minutemail.co.za",
  "10minutemail.com", "binkmail.com", "bobmail.info",
  "bouncr.com", "brefmail.com", "bumpymail.com",
  "burnthespam.info", "bustmail.com", "byom.de",
  "casualdx.com", "centermail.com", "centermail.net",
  "chammy.info", "clipmail.eu", "clrmail.com",
  "cool.fr.nf", "courriel.fr.nf", "courrieltemporaire.com",
  "crapmail.org", "crazymailing.com", "cubiclink.com",
  "cust.in", "cuvox.de", "d3amil.com",
  "dacoolest.com", "dandikmail.com", "dayrep.com",
  "dcemail.com", "deadaddress.com", "deadspam.com",
  "delikkt.de", "despammed.com", "devnullmail.com",
  "dfgh.net", "digitalsanctuary.com", "dingbone.com",
  "discard.email", "discardmail.com", "discardmail.de",
  "disposable.cf", "disposable.ga", "disposable.ml",
  "disposableaddress.com", "disposableinbox.com", "dispose.it",
  "disposeamail.com", "disposemail.com", "dispostable.com",
  "dodgeit.com", "dodgit.com", "dodgit.org",
  "dontreg.com", "dontsendmespam.de", "drdrb.com",
  "drdrb.net", "droplar.com", "dropmail.me",
  "duam.net", "dudmail.com", "dump-email.info",
  "dumpandjunk.com", "dumpmail.de", "dumpyemail.com",
  "e-mail.com", "e-mail.org", "e4ward.com",
  "easytrashmail.com", "ee1.pl", "ee2.pl",
  "eelmail.com", "einmalmail.de", "einrot.com",
  "einrot.de", "eintagsmail.de", "email-fake.cf",
  "email-fake.com", "email-fake.ga", "email-fake.gq",
  "email-fake.ml", "email-fake.tk", "email-free.ml",
  "email-free.tk", "email60.com", "emailage.cf",
  "emailage.ga", "emailage.gq", "emailage.ml",
  "emailage.tk", "emaildienst.de", "emailgo.de",
  "emailias.com", "emailigo.de", "emailinfive.com",
  "emaillime.com", "emailmiser.com", "emailproxsy.com",
  "emailresort.com", "emails.ga", "emailsensei.com",
  "emailsending.eu", "emailspam.cf", "emailspam.ga",
  "emailspam.gq", "emailspam.ml", "emailspam.tk",
  "emailtmp.com", "emailto.de", "emailwarden.com",
  "emailxfer.com", "emz.net", "enterto.com",
  "ephemail.net", "etranquil.com", "etranquil.net",
  "etranquil.org", "evopo.com", "explodemail.com",
  "eyepaste.com", "fakeinbox.com", "fakeinformation.com",
  "fakemail.fr", "fakemailz.com", "fammix.com",
  "fansworldwide.de", "fantasymail.de", "fastacura.com",
  "fastchevy.com", "fastchrysler.com", "fastkawasaki.com",
  "fastmazda.com", "fastmitsubishi.com", "fastnissan.com",
  "fastsubaru.com", "fastsuzuki.com", "fasttoyota.com",
  "fastyamaha.com", "fightallspam.com", "filzmail.com",
  "fixmail.tk", "fizmail.com", "fizyeta.com",
  "flyspam.com", "footard.com", "forgetmail.com",
  "fr33mail.info", "frapmail.com", "freemails.cf",
  "freemails.ga", "freemails.ml", "friendlymail.co.uk",
  "fuckingduh.com", "fudgerub.com", "fux0ringduh.com",
  "fyii.de", "garliclife.com", "gehensiuli.com",
  "get-mail.cf", "get-mail.ga", "get-mail.ml",
  "get-mail.tk", "get1mail.com", "get2mail.fr",
  "getairmail.cf", "getairmail.com", "getairmail.ga",
  "getairmail.gq", "getairmail.ml", "getairmail.tk",
  "getmails.eu", "getonemail.com", "getonemail.net",
  "ghosttexter.de", "girlsundertheinfluence.com",
  "gishpuppy.com", "goemailgo.com", "gorillaswithdirtyarmpits.com",
  "gotmail.com", "gotmail.net", "gotmail.org",
  "gowikibooks.com", "gowikicampus.com", "gowikicars.com",
  "gowikifilms.com", "gowikigames.com", "gowikimusic.com",
  "gowikinetwork.com", "gowikitravel.com", "gowikitv.com",
  "grandmamail.com", "grandmasmail.com", "great-host.in",
  "greensloth.com", "greermail.com", "guerillamail.biz",
  "guerillamail.com", "gustr.com", "h8s.org",
  "hacpcc.com", "haltospam.com", "hat-gansen.de",
  "hat-sellers.de", "hatpuppy.com", "hattonland.com",
  "hates-a-spy.com", "herp.in", "hidzz.com",
  "hotpop.com", "hulapla.de", "ichimail.com",
  "imails.info", "infocom.zp.ua", "ipoo.org",
  "irish2me.com", "iwi.net", "jsrsolutions.com",
  "kein.hass.frau", "kook.ml", "kostenlose-mailadresse.de",
  "kroweb.org", "lawl.gq", "lhsdv.com",
  "lortemail.dk", "lr78.com", "lukop.dk",
  "m21.cc", "maileater.com", "mailexpire.com",
  "mailfa.tk", "mailguard.me", "mailhazard.com",
  "mailhz.me", "mailmate1.net", "mailme24.com",
  "mailmetrash.com", "mailmoat.com", "mailnesia.com",
  "mailnull.com", "mailorg.org", "mailpick.biz",
  "mailproxsy.com", "mailquack.com", "mailrock.biz",
  "mailsac.com", "mailscrap.com", "mailshell.com",
  "mailsiphon.com", "mailslite.com", "mailtemp.info",
  "mailtome.de", "mailtothis.com", "mailtrash.net",
  "mailtv.net", "mailtv.tv", "mailuntil.com",
  "mailzilla.com", "makemetheking.com", "manifestgenerator.com",
  "manybrain.com", "mbx.cc", "meltmail.com",
  "mezimages.net", "migmail.pl", "migumail.com",
  "mindless.com", "mintemail.com", "mmmmail.com",
  "moakt.com", "moncourrier.fr.nf", "monemail.fr.nf",
  "monmail.fr.nf", "monumentmail.com", "mx0.wwwnew.eu",
  "my10minutemail.com", "myalias.pw", "mycleaninbox.net",
  "myemailboxy.com", "mymail-in.net", "mymailoasis.com",
  "mymailp.com", "mynetstore.de", "mypacks.net",
  "mypartyclip.de", "myphantom.com", "mysamp.de",
  "myspaceinc.com", "myspaceinc.net", "myspaceinc.org",
  "myspacepimpedup.com", "mytemp.email", "mytempemail.com",
  "mytempmail.com", "mytempmail.de", "mytempmail.org",
  "mytempmails.com", "mytmp.email", "mytrashmail.com",
  "nabala.com", "neomailbox.com", "nepwk.com",
  "netmails.com", "netmails.net", "neverbox.com",
  "nice-4u.com", "nincsmail.hu", "no-spam.ws",
  "nomail.xl.cx", "nomail2me.com", "nomorespamemails.com",
  "nonspam.eu", "nonspammer.de", "noref.in",
  "nospam.ze.tc", "nospam4.us", "nospamfor.us",
  "nospammail.net", "nospamthanks.info", "nowmymail.com",
  "nurfuerspam.de", "nuts22.com", "nyc.com", "nyxmail.com",
]);

const DISPOSABLE_KEYWORDS = [
  "tempmail", "temp-mail", "throwaway", "disposable", "trashmail",
  "fakeinbox", "dropmail", "getairmail", "maildrop", "guerrillamail",
  "spamgourmet", "mailinator", "yopmail", "jetable", "wegwerfemail",
];

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return false;

  if (BLOCKED_DOMAINS.has(domain)) return true;

  for (const keyword of DISPOSABLE_KEYWORDS) {
    if (domain.includes(keyword)) return true;
  }

  const parts = domain.split(".");
  if (parts.length > 2) {
    const rootDomain = parts.slice(-2).join(".");
    if (BLOCKED_DOMAINS.has(rootDomain)) return true;
  }

  return false;
}

export function isPlusAddressedEmail(email: string): boolean {
  return email.includes("+");
}
